#+TITLE: Wicst Data Organization
#+TODO: TODO(t) REVISIT(r) REVIEW(v) | DONE(d) IGNORED(i)

* General Todo
** create custom logins for gregg and adam?
** cut as grouped increment of sequence in table?
- not sure this is a good idea, as for pastures, suppose 1 greenchop, then 3 biomassings. Is the exclosure cut numbered 1-4 or 1, 1, 2, 3?
  - i think it should be 1123... its easier to maintain. It should also be nested within coordinate though.
- You need to code this as a trigger, not in the table definition
#+begin_src sql
CREATE TRIGGER trg_GroupSequence
ON Sales
AFTER INSERT
AS
BEGIN
    WITH cte AS (
        SELECT
            SaleID,
            ROW_NUMBER() OVER (PARTITION BY Region ORDER BY SaleID) AS GroupSequence
        FROM
            Sales
    )
    UPDATE s
    SET GroupSequence = cte.GroupSequence
    FROM Sales s
    INNER JOIN cte ON s.SaleID = cte.SaleID;
END;
#+end_src
* Project Design
The project can be split up into a three-tier architecture of Presentation/Logical/Physical. This is similar to business intelligence "[[https://docs.oracle.com/en/middleware/bi/analytics-server/datamodel-oas/semantic-models-architecture.html][semantic architecture]]" or web design's three-tier architecture. I like to think of it in analogy to statistical contexts as: Raw Data -> Modeling -> Results

1. Presentation
   - This tier is customized for the end user and has the highest level of abstraction over the raw data. This should be easy to use for non-technical users, and should not require specialized knowledge of the data curation or sources of the data. There are often many services that this presentation tier will have, each built for specific purposes
2. Logical
   - This tier should contain all the "business logic" of what this project offers. In this case, I would presume this mostly contains a series of statistical models that summarize the data. If data visualizations and data reports are desired in the presentation tier, then this tier will contain all the code that goes behind generating those reports. Ideally, the structure of this tier matches the design of the presentation tier, and is relatively robust to changes that happen in the Physical and Presentation tier. Many times this will result in a series of "endpoints" in which the presentation tier can consume data in a consistent format.
3. Physical
   - This tier is how the data is actually stored and organized. The design of these databases and implementation of this data should be highly dependent on internal operations, and should be regularly curated so that the data is clean and organized. We will aim for a balance of consistency, availability, and robustness.
** Customers (Presentation Layer)
*** Questions for each Customer
**** What is the reason for them to use this data?
- "We need to see summaries of this data for grant writing"
- "We would like to see recommendations for seeds in the upcoming planting season"
**** Are there any data privacy concerns that should be addressed?
- Do we need to set any limits on how much/how often they will be accessing this data?
- Are there any legal restrictions that need to be met?
**** Who and how will they be accessing the Data?
- Access through the browser? through their phone?
- Will they need direct access to the data? Or be able to submit requests for updating the data?
- User authentication or verification?
**** How critical is this Customer?
**** How should they be able to access the data?
- Are they using this data in production, and building tools on top of this? Will they need an API to access our data?
- Do they want to be able to download csv files of their summary?
- What visualizations or reports might they want, and how frequently?
** Statistical Analysis (Logical Layer)
*** How should the implementation of analyses be done? R? Python?
*** What summaries would be the most useful?
*** Do we need to create logic for customers to update our data? or just read?
** The Data (Physical Layer)
*** What is the structure of the current data?
*** What is necessary to keep and clean?
*** How often will the data need to be updated and read from?
*** Where should this be hosted?

* Execution Plan
Time will be split evenly across the three layers of the project design: Presentation(33%), Logical(33%), Physical(33%). The time spent on the presentation layer and physical layer I anticipate will need most of your time, as those are very "practice dependent".

I'll propose that my work will have roughly 3 phases, and progress in mostly a top-down manner.

1. Minimum Viable (~10%)
   - We will identify /one/ customer, and create all three layers of the project to service the one customer. There will be strict boundaries on the data integrated into the minimum product
   - The customer identified will be representative of general pattern of needs in the project, and feedback sessions will iterate on the basic product until it is serviceable and can be utilized live.
2. Design for current customers (~60%)
   - Taking into consideration the aggregate needs of the customers /currently/ serviced, we will create a design that adheres best to the current utilization of data. Database schemas have appropriate identifying information, security practices are implemented, etc.f
     - Flowcharts? Page 12 [[https://cms.library.wisc.edu/archives/wp-content/uploads/sites/21/2015/06/2014-Electronic-Business-Communication-and-University-Records.pdf][2014 Business Communication and University Records]]
   - Customer needed data will be curated and cleaned, organized into well-defined schemas with identifying information
   - Data Retention Schedules will be developed, with policies on when and how data will be curated.
     - [[https://www.library.wisc.edu/archives/records-management/uw-madison-records-retention-schedules-and-disposition/][retention schedules at UW]]
   - Data stewards and responsibilities will be identified and assigned.
3. Design for scalability/persistence (~30%)
   - I will try to make this system healthy enough to run on its own after I'm no longer on this project.
   - This will be writing appropriate documentation, and passing on the necessary skills to keep these services in operation.
   - Hosting services will also be a considderation. I will prioritize looking for a department, campus, commerical solution in order keep these services available.
     - department will also have web hosting solutions available if needed
     - RPosit has some platforms for computing machine time.
     - DOIT has solutions for Oracle,MSSQL, and dedicated staff to keeping these services running.
     - There are associated costs with keeping these databases up as well, and I would also rely on their expertises in this regard. If we choose one of these routes, I'll be responsible for communicating our project's technical needs. I will try to come up with reasonable cost estimates for the upkeep of this project.
     - [[https://storage.researchdata.wisc.edu/][Research Data Services]] also has some campus related tools we may be able to use, including cloud services like Amazon web services, and Azure.
     - At this time, I'm considering single file endpoints, with Rposit for computing, UW for web hosting. Sqlite can be created for single file endpoint.
   - Can also develop and track project metrics to make it easier to justify for future funding projects.
* Background Information
** Farming
*** Fertilizers
- three numbers for starting fertilizers 9-11-30 means Nitrogen-Phosphorus-Potassium
- Liming is mostly for controlling ph of the soil, measured by eutralizing Index. It's the carbonate CO3-2
  - 80-89 grade is the neutralizing index zones, so the higher the index zone, the higher the quality of lime. It's finer or has more carbonate.
** Terminology
- bu/a :: bushel per acre
- T/a :: tons per acre
- PPNT :: Preplant soil nitrate test
  + measures residual/carryover N
- PSNT ::
- leaching ::
- os :: oat straw
- of :: oat forage (oatlage)
- wg :: wheat grain
- ws :: wheat straw
- hay tedding :: lifting and separating hay to speed up dry down time. "fluffing"
- windrow :: row of cut hay/small grain crop. Normally before being baled combined or rolled
- raking :: seems another method of making windrows,
- hay :: cut grass left out to dry, generally used for food.
  - 10% moisture
- straw :: wheat/oats/barley after the combine that cuts off the berry stuff on the top.
  - generally used for bedding, decoration, scattered etc.
- hay bale  :: a bundle that has more moisture than straw bale
- straw bale :: oat/wheat straw after the cutting, super dry
- baleage :: fermented forage >  "baled" > wrapped in a tube or plastic
  - 45-55% moisture
  - basically skip the
- haylage :: forage chopper > bagged/silo/bunk/covered
  - 60-70% moisture ("high moisture haylage")
  - called such because it's left to wilt for shorter period of time than normal hay
- forage ::
- silage :: anything stored in silo
- ensile :: put into a silo to preserve as silage
- plowing :: technically a type x of tilling but more intense
- moldboard plowing :: more scoop and flip action of plowing
- chisel plowing :: more claw deep and disturb type of plowing
- flail mower :: cutter adapted for occasional immovable objects, will just "not cut" the rock instead of catching it and throwing it.
  - also can cut lower to the ground.
- cultivator :: it's like mixing top soil... technically tilling. but "no-till system"
- tine weeding :: little claw like thing dragging behind
- ANPP :: aerial net primary production
  - seems like measuring the surface area and productivity of the cover.
  - they have canapeo measurements
- paddock :: enclosed area for pasturing or exercise animals
** Data
- each season has multiple crops, wheat (grain, straw) and alfalfa (multiple cuts)
- two sites ARL and LAC. No LAC past 2003
- system 1:6, 14:15.
  - 14 only shows up in 2002, and 15 only shows up in 1999-2002. These look like modifications of 4 and 5. From notes tab:
    #+begin_quote
    all plots for cuts 3 and 4 of CS4 and CS5 were not sampled for quality analysis (not sure why)
    #+end_quote
- blocks 16 each year starting in 2017, 14 each year from 1989 - 2016.
- system 2 has only filler corn the first year
- system 3: 1989, 1990 don't have all 3 crop1. 2019 is missing wg?
  - 1994, LAC, there's one wg rotation
- oat grain crop1
** Actionable
*** 1989 system 2 has potential mislabel
- supposed to be corn/sb but two rows of block 1 have both labeled as corn and none with soybean.
  #+begin_src R
wicst_raw |>
  filter(system == 2) |>
  select(year, crop1, crop2, crop3) |>
  distinct(year, crop1, crop2, crop3) |>
  xtabs(~year + crop1, data =  _)
  #+end_src
- it's possible this is just how the trial started? It's unclear how this
** Treatment
- "c silage" is 2017-2019
- "c_silage" is 2020-2023
** Soil Metric
cash cornell guide
- POM-C :: particulate organic matter
  - indicator for management practices
- PLFA :: phospholipids fatty acids
- SOC :: soil organic carbon
- Total C+N ::
- 24-hr C :: biotic indicator
- ACE protein :: indicator of fungi
- Aggregate stability ::
* Table Documentation/Notes
** Global ID Structure
H2023_A204MMS_CS_1
- H...._......._.._. (action)
  - H :: harvest
  - L :: direct harvest Loss?
  - G :: global harvest loss
  - B :: biomassing
  - C :: Canopeo?
  - S :: plantings/seedings
  - M :: manuring
  - F :: fertilizing
  - P :: pesticidings
- .YYYY_......._.._. (year)
  - the 4 digit year
- ....._A......_.._. (site)
  - A :: Arlington
  - L :: Lakeland
- ....._.PPP..._.._. (plot)
  - 3 digit plot id
- ....._....MM._.._. (section)
  - MM :: Main
  - MA :: Macro (biofuels)
  - MI :: Micro (biofuels)
  - WW :: West (EI)
  - ES :: East Strip
  - WS :: West Strip (corn silage)
- ....._......C_.._. (coordinate)
  - S :: South
  - C :: Central
  - N :: North
- ....._......._CN_. (product)
  - very loose description of the product
- ....._......._.._1 (cut)
  - 1 - 5 currently for cut from location
  - signifies temporal
** plots
- system should be a property of plots... but the lakeland plots are an excepttion to that requirement what to do here...
** SubPlots
** SidePlots
for corn silaging. ID will be
** Fuelplots
captures the macro and micro size plots for the prairie location
** Plantings
** Manurings
- include just source
- source (liquid, solid)
- methods (broadcast, injected)
** Fertilizings
- uan32 : can just put 32-0-0-0-0
- [ ] split out lime into a different table, just need the grading, see ch5 of extension pdf
- [ ] N, p2o5, k20, s, ... as column names
** Tillings
*** Fields
- type (primary, secondary, tert)
- date
- implement (field cultivator, rotary hoe, tine weeder, row cultivator, strip tiller, cultipacker, chisel plow, disk-chisel plow, disk)
- passes
** Pesticidings
*** Fields
- date
- common name (roundup/power max, fs transform plus)
- category (herbicide, insecticide, fungicide, adjuvant)
  - ams is an adjuvant
  - fs transform plus is adjuvant
- rate
- rate unit
** Pesticides
separate out the types of pesticides here, and more detailed information about them, posibilities
** Canopeo
*** Fields
**** canopeo_id
**** coverage_date
**** plot
**** coordinate
**** percent_cover
** Harvestings
- "Collecting a product off the field, no matter the form"
*** Fields
**** plot
**** harvest_date
**** harvest_area
**** product
**** product_description
** biomassings
it looks like 1 evaluation per season for everything except pasture. In the datasheets,even at a single date, there are multiple "bags", if we record the bag weight for those instances, each row in the table is a bagging. I'd say it should be a cut evaluation or something. plot -> cut ->
- the length of plot changes for each plot cutting... so if pasture and anpp go into the same table, each cut by definition can't be the same quadrant because they will have different areas. we should consider plot(cut x quadrat)
*** Questions
- [X] how important is % moisture when evaluating this... it seems pasture its recorded, but anpp like alfalfa is not.
- [X] alfalfa is harvested, but then also evaluated later in the season?
- Does the cutting in a field season happen in the exact same quadrant?
- Do the cuts on N, C, S happen at the same time? can we assume that they might be different?
*** Fields
**** plot (subplot)
"section", main, e1, e2, e3, e4 should be captured or implied by the plot and the table, so doesn't need duplication in this column
**** sample_date
**** coordinate
  we need this because for the canopeo measurements, even within small EI plots with SW, there are 3 measurements being taken, one for south, central and north. Furthermore, the locations in the main plots are also sometimes 3 measurements, though often the sampling itself is just "center".
  For pasture, there's multiple locations that rotate for biomassing
  multiple locations are captured _sometimes_, idk if default should be center if only 1?
  - south
  - central
  - north
  - paddock 1
  - paddock 2
  - paddock 3
  - paddock 4
  - paddock 5
  - paddock 6
  - paddock 7
  - paddock 8
**** cut
- pastures need a cut column
**** biomassing_area
**** method
there's the above ground quadrat methodology, which is normally .5m2 or 1m2 quadrats, and the below ground stuff was .3
- quadrat
- undercutting
**** crop_component
- shoots
- roots
- both
**** crop
- alfalfa
- weeds
- oats
- berseem clover
- red clover
- residue
  - dead stuff, but different than weeds.
- pasture
** BiomassingDetails
*** Fields
**** biomassing_id
**** biomass_width
**** biomass_length
**** bag_weight
** HarvestPlantings
- linkage table
- resolves many to many relationship between Harvests and Plantings because multiple crops can be involved in a harvest (oats/alfalfa). Multiple harvests can be made of a single crop (alfalfa).
- plantings may not be harvested, instead they may be tilled into the land, or they may simply die. but the reverse harvest must have
** HarvestingDetails?
This table preserves some of the intermediary tools used to calculate final harvest numbers. Generally there are additional implements used, such as bags for straw and wagons for bales. We require that these numbers be associated with specific harvests. If we harvest 3 cuts of alfalfa through the season, it's possible each cut will use a different bag.
TBD: do we really need wet -> dry -> bag?
*** Fields
**** harvesting_id (PK, FK)
**** wet_bag_weight
**** dry_bag_weight?
 - I believe some datatables also measure the dry bag... is this because the bag itself has some moisture?
**** wagon_color
**** wagon_weight
**** bag_and_wet_product
**** bag_and_dry_product
**** num_bales
- sometimes meta information of how many bales were measured... needed? in comments?
- 2021_harvests_wheat_straw has an example.
**** comments
 - since this is 1-1 with the harvest, this will also be anything related to the harvest itself
** HarvestLosses
- captures any losses recorded in the field during harvest times, needs to be separate because sometimes the "true" yield reflective shouldn't adjust for these losses. losses happen in the real world too.
- there are TWO types of losses, those that affect all area for cultivator blight, and those that you directly subtract from the harvest area
- We do NOT track losses that do not affect final harvests, that is not the purpose of this table, i.e. filler corn reductions in the side plots
*** Fields
**** harvestingloss_id                                                     :PK:
**** harvesting_id                                                         :FK:
- link to harvesting_id, where there's plot info and such
**** harvest_loss_area
- the direct loss to the harvesting area, most important
** DirectLossDetails
- If "direct loss" is not known, the details will contain how much was damaged and the proportional factor. Unfortunately this normally happens when
*** Fields
**** harvestingloss_id
**** assessment_total_area
- assessment_total is the denominator for the final correction factor assessment_loss_area / assessment_total_area
**** assessment_total_length
- is it helpful to know how area was calculated? I guess?
**** assessment_total_width
**** assessment_loss_length
**** assessment_loss_width
**** assessment_loss_area
**** assessment_loss_rows
**** loss_rows
**** loss_width
**** loss_length
**** loss_reason?
- free text for reason?
- can potentially systematize and move "up" to harvestloss table
**** loss_location?
- free text for describing where?
**** comments
** SystematicLoss
- these apply to the HARVEST AREA. i.e. .2 loss fraction means that the area was reduced by 20%. this is important distinction because in the yield calculation the adjustment is in the denominator. For example, 20% systematic loss with 20000 sqft and 1000 dry weight yield means 1000 / (20000 * .8). This is different than saying the yield increased by 20% b/c 1000 / (20000 * .8) != 1000 * 1.2 / 20000.
** SystematicHarvestLossDetails
*Nah, still no. We can make this a game time decision if we just track assessment area and damage.*
- a reason for SPLITTING these losses, is that we MUST make the assumption by default that every loss in harvest losses is mutually exclusive.
I think there needs to be a different table for systematic changes, because all of this needs to be combined into a multiplicative factor for harvest area lost. That means there's multiple fractions like 1/5 for water loss, 1/7 for lodging, etc, but there's multiple things you could do for each fraction, i.e. assume they're independent! in which case it's not the simple sum, but you need inclusion exclusion formula for calculating loss.
- assume mutual exclusion (this is the easiest case when multiple rows are evaluated over the same assessment area, and is probably the most common case).
** HarvestingDimensions
Each harvest must capture an /intended/ area. These dimensions are not always given, but given that the harvest area for some plots will vary depending on the measurements taken each year, it's important that these intermediary numbers also be preserved as those measurements will affect yield/area calculations. Finally, there is some noted confusion about what "numbers" to use for length/width in the datasheets, so it would be nice to see if there are errors being made about particular years. The numbers are associated with single harvests. should be a 1-1 optional participation?
TBD: maybe merged with details table
- harvesting_id (PK, FK)
- plot
- harvest_length
- harvest_width
** Undercutting?
they were using underccuts to measure biomassings... maybe ignore?
*** using the undercuts
* Relationships
- sites-plots
- plots is an identifying relationship
** HarvestLosses 3o---| Harvestings
- Losses refers to harvestings
- one to many because many losses in a field at harvest time, different sections of plot
- Non-identifying because
  - the distinction is actually not THAT important, since we're using a surrogate key (not a composite) for harvest losses, ie, it's going to be redundant to make the harvest id also a key, because our surrogate key harvestlosses_id will identify the loss.
- harvestloss -> harvestings participation is MANDATORY because you can't have a loss without a harvest
- the other way harvestings -> loss is OPTIONAL because not all harvestings will have a loss.
  - on the joins... you'll just have to rememeber to hit this table, and zero out the harvests without any values here.
** HarvestingDetails |o---| Harvestings
- details refer to harvestings
- 1-1 because... only one action being described
  #+begin_quote
CREATE SCHEMA IF NOT EXISTS `myagg` DEFAULT CHARACTER SET utf8
CREATE TABLE IF NOT EXISTS `myagg`.`EIHarvests?` (
)
ENGINE = InnoDB
  #+end_quote
** BioDetails -> Bio <- Yieldings
- why doesn't this work
- it's backward, because now you're trying to say yield_id is a foreign key from two places, and that same field can't point to two different places
  - bio.id <- yield.id -> harvest.id (incorrect)
  - bio.id -> yield.id <- harvest.id
- I think you have to implement it as Bio -> Yieldings... can you implement it as a check?
* Style Guide
** Table Names
- lowercase and all plural
- SAS needs all the tablenames to be lowercase otherwise they won't get imported
* GCP
- postg
** postgres db
- pass: Sanfordlab
- myliou:iamtheadmin
** Journey
- download gcloud cli through the sdk, enable IAM,
** Getting into the db
1. Direct connection
   The database will have a public facing IP address. If you try to connect to that directly ip, port 5432, then you'll be asked username/password and you're in! Since this is weaker in security, google will require that you specify which ip addresses you'll be connecting from, so that people can't just bruteforce attack your database. You need to specify a mask of ip addresses as a range.
2. SQL Proxy Auth
   Essentially you're setting up a tunnel from your computer to
** SQL Proxy Auth
A "proxy" is just another networking way of connecting to your database.
- setup a dedicated host
* MSSQL
** Login
Database <WEIR> has been setup on Prod (stanley.doit.wisc.edu), and Development (carrington.doit.wisc.edu)

Dev:
WEIR_dbo  PASSWORD= Ty&xJUmh!X*AYp
WEIR_User PASSWORD= gIP#mRoA2t9BAz
WEIR_Read PASSWORD= 8q4r^W@1^RUJRD

Prod:
WEIR_dbo  PASSWORD= @Dd8jGMSfyJ%P$
WEIR_User PASSWORD= 0xt&j8nZ!WSDGh
WEIR_Read PASSWORD= 8R*BCYGY$ms1a@
** Custom Login
gregg_read PASSWORD=
** Install
*** ODBC drivers
Need to install [[from ][odbc drivers]]
#+begin_src
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_ACCEPT_EULA=Y brew install msodbcsql18 mssql-tools18
#+end_src

- brew output
  #+begin_quote
  If you installed this formula with the registration option (default), you'll
  need to manually remove [ODBC Driver 18 for SQL Server] section from
  odbcinst.ini after the formula is uninstalled. This can be done by executing
  the following command:
    odbcinst -u -d -n "ODBC Driver 18 for SQL Server"
  #+end_quote
*** sas access
#+begin_quote
libname mssql sqlsvr complete="DRIVER={SAS ACCESS to SQL Server};
HOST='sqlserverdb.mycompany.com';DB=mydb;PORT=1433;
AuthenticationMethod=4;
EncryptionMethod=0;"
user=mydom\myuserid password='MyPassword1!';
#+end_quote
*** scrollable cursors?
- "As a best practice, set the EnableScrollableCursors ODBC driver option to 3." [[https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/acreldb/p02o7pdhah9nusn1dgqjgo66ibgs.htm][sas access mssql]]
*** Firewall
* Front End/ETL Solutions
** Bettyblocks
** SSIS Package
- i think dstx file? that you just run from local machine and it just works
** Power Automate
* Notes
** Meeting
- meeting in field, if grain, normally it's just calculated on site with the moisture,
- if it's oatlage or forage, throw it into a freezer and the deviation is... if it's a biomassing, then there's wet and dry weight,
- 2016 - 2017
- 2013-2015 rrl? moisture?
** [2024-12-12 Thu] yield review
- 13 and 13.5 transition, for wheat grain.
** ENTRY anomaly
- 1993: we believe there was significant winter kill in
- 1993: pasture was established in 1990, in 92, we interseeded more plants on top of the established pasture, it just takes a while to get going.
  - 4/30/92 we planted brome, timothy, and orchard grass (NA)
  - 1993 plots were a struggle to figure out. We believe there might be some mislabels in 1993, as the agcalendar was difficult to interpret.
- hole and you fill in plant
- interseed :: you plant and simultaneous
- interseed replant :: already something established, for example alfalfa, remedy stand issue
- replant :: we tilled everything up and start over again
** Db Design Review
- have to feed rye with manure, but originally did not need manure because just harvesting soybean. It's wasting manure because legumess fix nitrogen. But needed a LOT of rye biomass
- why barley? roller crimp before soybean, but delays the process too long, but then you can't plant a winter wheat. Barley becomes the small grain so that we can get an earlier harvest, in order to have the cover crop. corn -> soybean -> small grain
** Fertilizings with Nolan
Phosphorus and Potassium HAS to be preplant, about 1 week before planting date for Corn, soy, wheat
** dflkjdf
josh passed away, 2013 can you continue this,janet was the one that
** [2024-10-18 Fri] NSCR Kristin Foehringer
- started as soil scientist, wrangling planners and conservation planning process at, "atcat50"
- "farm lab" at dairy science research lab
*** background
erin & gregg asked to expand socnet that aligns with the government nrce. want to monitor more soils.
*** powerpoint
- reactive,if there's a problem, NRCS purpose. they don't put in a gully to prevent erosion for example
- constrained by farm bill, has to be written into law for them to be more preventative not reactive
- phase 3, need to quantify what they're doing to report to the american people
- CEMA, farm scale forested land, asses soil organic stock monitoring, they contract it out, farmers request, they contact someone qualified, and they would pay the farmer to do it.
  - "CEMA 221" bachelors in soils eg, side job.
  - you are also the person owning the data. "QI" qualified individual
  - opportunity to expand socnet
- USDA is starting to provide information on carbon markets, and farmers can "arm them selves" against people tyring to buy their carbon credits
**** comet
usda's response for monitoring.
- "the blue book" has ab unch of equations and such, sthe impact of greenhouse gasses and evaluation of practices
**** partnerships for climate smart commodities
- grants for, IRA funds and they're. iowa soybean association, wisconsin farmers association. invest climate commodites, and doling out to farmers to implmeent those climate friendly things. But they eventually enter their data into COMET to see how much they get.
*** terminology
- PLU - planning land unit
- TSP - technical service provider
- QI - Qualified Individual
- COMET-farm - https://comet-farm.com/home, web monitoring
  - empirical model in dephth
- COMET-planner
- IPCC - international panel of carbon.. counting? panel for standardizing impact
- MMRV :: monitoring something something
- CENTURY :: soil carbon model biochemical models
- CRP :: land removed to plant corn...
  - contracts are 15 years and stuff
- STIR :: soil tillage intensity rating
- RUSSELL2 ::
** [2024-10-10 Thu] w/ doit database
*** Notes
- MSSQL server over 20 years
  - two shared, 2022, 2021 always on dedicated
  - development environment, production environment, regular database user, database owner user, read/write user, back it up, patching operating system, microsoft sql administrator, query, 24/7 shop, WAMS department kind of, and through their application, wisconsin public radio.
  - per month, hosting fee, how big it is, 100$ an hour for etl help, consulting
- no enterprise mysql support
- no postgress,
- Derek, team lead for oracle database hosting
  - Exodata
  - cloud at customer
  - storage
  - student systems, hr
*** Questions
- MSSQL vs Oracle, some geometry requests
- who's creating the user accounts and such, creating new views? sql.
- helping upload csv files to upload
- Maintain offsite backups and perform disaster recovery in case disaster destroys the database.
- Maintain and manage database at reasonably high availability at >99.99% uptime.
- Monitor log files and performance of database, ensuring optimum performance
- Schedule consistent maintenance on the server, including patching operating system
- Monitor security and prevent any unauthorized access to the database
- Manage user access and permissions by adding and removing users as needed
- Communicating and reporting signs of damage to data integrity, potential security vulnerabilities, scheduled maintainances and downtimes, and usage of computing and database resources.
** [2024-10-09 Wed] wisconet with david
- attendance: izzy, david, chris, david
- 4 instances of ec2, relational dbs, mysql.
- each station has a folder for achives
- normalzied everything for consistent measures, basically every column, boto3
** [2024-10-03 Thu] static ips
- Michael: 146.151.200.13
- Adam: 146.151.194.52
- Gregg: 146.151.200.14
** [2024-09-26 Thu] wheat yield, harvest/plant review, visit to farm
- [ ] bag weight, length, width to harvest table
- [ ] row spacing, planting depth to planting table
- ANPP? really should be a separate table as its another condsequence
- explanation of the wheat yields. The grain is cut off, then the straw is bagged as "wet", then set in a room to be dried
** <2024-09-06 Fri> Organic Marketing World, how
** [2024-09-16 Mon] First Meeting with Adam
*** "I want all of the soil test phosphorus data from your organic corn systems from 1990 to 2010"
